name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Install material theme
        run: pip install mkdocs-material==7.2.8

      - name: Install truly sane lists plugin
        run: pip install mdx_truly_sane_lists

      - name: Setup directory stucture for mkdocs
        env: # Or as an environment variable
          GH_PAT: ${{ secrets.GH_PASSWORD }}
        run: |
          # enable globing
          shopt -s nullglob dotglob extglob

          # move up one dir from repo
          cd ..

          # clean local copy of repo
          rm -r ibm-cloud-garage-training

          # clone main repo
          git clone https://enzobarrett:$GH_PAT@github.com/upslopeio/ibm-cloud-garage-training.git

          cd ibm-cloud-garage-training

          # setup folder heiarchy
          mkdir docs
          rm mkdocs-serve.sh
          cp -r !(.git|mkdocs|docs|.|..) docs/
          cp -r mkdocs/* ./
          rm -r mkdocs

      - name: Deploy to gh-pages branch
        env: # Or as an environment variable
          GH_PAT: ${{ secrets.GH_PASSWORD }}
        run: |
          # configure git
          git config --global user.email "mkdocs@upslope.io"
          git config --global user.name "mkdocs"

          # builds site and commits to gh-pages branch
          mkdocs gh-deploy

          # make sure branch gets pushed
          git push origin gh-pages
