site_name: Cloud Native Garage Method Boot Camp
site_url: "https://upslopeio.github.io/ibm-cloud-garage-training/"
theme:
  name: material
  custom_dir: custom_theme/
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
  palette:
    scheme: default
    primary: black
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  language: en
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.keys
nav:
  - Computer Setup:
      - Mac: computer-setup/mac.md
      - Windows: computer-setup/windows.md
      - IBM Cloud: computer-setup/ibmcloud.md
  - XP:
      - Overview: xp.md
      - Pair Programming: pair-programming.md
  - Coding:
      - React Intro Setup: react/README.md
      - JS Testing: tdd/README.md
      - React Testing: react/testing.md
  - Devops:
      - Tekton: tekton/README.md
      - Argo: argo/README.md
      - Sequence Diagram: argo/diagram.md
      - Notes: tekton/notes.md
  - Project Work:
      - Getting Started: projects/index.md
      - Assigning Permissions: projects/permissions.md
      - Playbacks: projects/playbacks.md
      - Presentations: projects/presentation.md
